spring:
  security:
    user:
      name: admin
      password: admin
  h2:
    console:
      path: /h2
      enabled: true
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
        ddl-auto: create
management:
  endpoints:
    web:
      exposure:
        include: "*"
